In [2]:
import pandas as pd
import numpy as np

# Q1. Pandas version

In [3]:
pd.__version__

'1.1.3'

In [4]:
df=pd.read_csv("laptops.csv")

In [5]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

# Question 2. Records count

In [6]:
df.shape[0]

2160

# Question 3. Laptop brands

In [7]:
df['Brand'].value_counts()

Asus                415
HP                  368
Lenovo              366
MSI                 308
Acer                137
Apple               116
Dell                 84
Microsoft            77
Gigabyte             48
Razer                37
Medion               32
LG                   32
Alurin               29
PcCom                24
Samsung              22
Dynabook Toshiba     19
Vant                 11
Primux                8
Deep Gaming           8
Innjoo                6
Thomson               4
Prixton               3
Millenium             2
Jetwing               1
Realme                1
Denver                1
Toshiba               1
Name: Brand, dtype: int64

In [17]:
df['Brand'].nunique()


27

# Question 4. Missing values 

In [9]:
df.isna().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

# Question 5. Maximum final price

In [19]:
#df[df['Brand'] == 'Dell'].max()
df.groupby('Brand')['Final Price'].agg(['min','mean','max'])


min         mean      max
Brand                                          
Acer               264.14  1001.285766  3691.00
Alurin             239.00   484.701379   869.00
Apple              299.00  1578.227672  3849.00
Asus               239.25  1269.380699  5758.14
Deep Gaming       1334.00  1505.377500  1639.01
Dell               379.00  1153.839881  3936.00
Denver             329.95   329.950000   329.95
Dynabook Toshiba   397.29   999.197895  1805.01
Gigabyte           799.00  1698.488958  3799.00
HP                 210.14   952.628478  5368.77
Innjoo             251.40   347.888333   431.38
Jetwing            469.27   469.270000   469.27
LG                 609.04  1730.028438  2399.00
Lenovo             239.00  1087.723880  5018.14
MSI                444.19  1913.451006  7150.47
Medion             246.89   905.331875  3799.00
Microsoft          599.01  1595.543247  3747.91
Millenium         1640.98  1976.845000  2312.71
PcCom             1049.00  1606.762917  1949.90
Primux             208.99   339.618750   599.41
Prixton            246.95   292.280000   329.95
Razer             1232.74  3265.701622  4999.01
Realme             999.00   999.000000   999.00
Samsung            365.90  1595.511364  3699.01
Thomson            201.05   316.860000   436.56
Toshiba            799.00   799.000000   799.00
Vant               632.00  1047.455455  1217.01

In [23]:

df[df.Brand == 'Dell']['Final Price'].max()

3936.0

# Question 6. Median value of Screen 

In [24]:
median_screen=df['Screen'].median()
median_screen

15.6

In [27]:
mode_screen=df['Screen'].mode()[0]
mode_screen

15.6

In [33]:
df['Screen'].fillna(mode_screen).median()

15.6

# Question 7. Sum of weights 

In [14]:
df_select=df[df['Brand']=='Innjoo']
df_select

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [15]:
df_select=df_select[['RAM','Storage','Screen']]
df_select

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [16]:
X=np.array(df_select)

In [17]:
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [18]:
XTX=X.T.dot(X)

In [19]:
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [20]:
XTX_inverse=np.linalg.inv(XTX)

In [21]:
XTX_inverse

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [22]:
y=np.array([1100, 1300, 800, 900, 1000, 1100])

In [23]:
y

array([1100, 1300,  800,  900, 1000, 1100])

In [24]:
w=(XTX_inverse.dot(X.T)).dot(y)

In [25]:
w

array([45.58076606,  0.42783519, 45.29127938])

In [26]:
sum_w=sum(w)

In [27]:
sum_w

91.2998806299555